name: lartpc2D-rl
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2019.10.16
  - cairo=1.16.0
  - certifi=2019.9.11
  - dbus=1.13.6
  - expat=2.2.5
  - ffmpeg=4.1.3
  - fontconfig=2.13.1
  - freetype=2.10.0
  - gettext=0.19.8.1
  - giflib=5.1.9
  - glib=2.58.3
  - gmp=6.1.2
  - gnutls=3.6.5
  - graphite2=1.3.13
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - harfbuzz=2.4.0
  - hdf5=1.10.5
  - icu=64.2
  - jasper=1.900.1
  - jpeg=9c
  - lame=3.100
  - libblas=3.8.0
  - libcblas=3.8.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libiconv=1.15
  - liblapack=3.8.0
  - liblapacke=3.8.0
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.0.10
  - libuuid=2.32.1
  - libwebp=1.0.2
  - libxcb=1.13
  - libxml2=2.9.9
  - lz4-c=1.8.3
  - ncurses=6.1
  - nettle=3.4.1
  - numpy=1.17.3
  - opencv=4.1.0
  - openh264=1.8.0
  - openssl=1.1.1d
  - pandas=0.25.2
  - pcre=8.43
  - pip=19.3.1
  - pixman=0.38.0
  - pthread-stubs=0.4
  - python=3.7.4
  - python-dateutil=2.8.0
  - pytz=2019.3
  - qt=5.9.7
  - readline=7.0
  - scipy=1.3.1
  - setuptools=41.4.0
  - six=1.12.0
  - sqlite=3.30.1
  - tk=8.6.8
  - wheel=0.33.6
  - x264=1!152.20180806
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.9
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.4.3
prefix: /home/mwm/anaconda3/rl_environments/lartpc2D-rl

